---
title: "Data Cleaning"
output: github_document
date: "2022-12-04"
---

```{r setup}
knitr::opts_chunk$set(message = FALSE)

library(tidyverse)
library(lubridate)
library(plotly)
```

Data input and cleaning 
```{r}
bakery_df =
  read_csv("./Data/Bakery_sales.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    unit_price = str_replace(unit_price, "€", ""),
    unit_price = str_replace(unit_price, ",", "."),
    unit_price = as.numeric(unit_price),
    product_name = article) %>% 
  filter(product_name != ".") %>% 
  select(-article)

bakery_df
```

One way anova test to see if the mean number of the sales are different for summer (Jun - Aug) and winter (Dec - Feb)  

```{r}
anova_df =
  bakery_df %>% 
  mutate(
    month = month(date),
    rev = quantity *unit_price 
  ) 
  summer_sales = 
    anova_df %>% 
    filter((month == 6) |(month == 7)|(month == 8)) %>% 
  group_by(month) %>% 
  summarize(summer_sales = sum(rev))
  
  winter_sales = 
    anova_df %>% 
    filter((month == 1) |(month == 2)|(month == 12)) %>% 
    group_by(month) %>% 
  summarize(winter_sales = sum(rev))

```


A pie chart showing the percentage of each product’s sale count (top 10)
```{r}
plot_pie =
  bakery_df %>% 
  group_by(product_name) %>% 
  summarize(n_obs = n()) %>% 
  arrange(desc(n_obs)) %>% 
  head(10) %>% 
  plot_ly(labels = ~product_name, values = ~n_obs, type = 'pie', colors = "viridis") %>% 
  layout(title = 'Top 10 favoriate bakeries',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

plot_pie
```


A line plot of trends showing total sale revenue by month (trend)
```{r}
plot_line =
  bakery_df %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(year = as.numeric(year),
         month = as.integer(month),
         day = as.integer(day),) %>% 
  group_by(year, month) %>% 
  mutate(rev = quantity * unit_price) %>% 
  summarize(month_rev = sum(rev)) %>% 
  
  plot_ly(x = ~month, y = ~month_rev, mode = 'lines+markers', alpha = 0.5)

plot_line 
```




